### PR TITLE
Bug fix: mandatory fields are handled better when not filled in

### LINKED ISSUE #62: nan is filled in when column is mandatory and cell is empty
This tricks the validation although nothing is present

### PR DESCRIPTION
**Pull request by bedroesb**
This PR fixes certain weird behaviors. Before when the table was not filled in at a column that is mandatory, or just NA, the validator would not complain. It would only complain when a field is missing that has a controlled vocabulary.

Now all mandatory attributes got wrapped with an if statement that stops the script when missing. It is done this way because if the `<key></key>` is included, but is empty, the validator will not complain, because it is present + now the error will not appear if the platform or instrument model is not given that lowercase can not be applied to nan objects. 

- [x] Terminates the program if a mandatory field is not filled in. This will close #62 
- [x] Better handling of Na values by setting them in pandas while parsing
- [x] Extensive testing. Tested with leaving out all types of values in the table. 
- [x] More useful logging. It will tell the user which row and column that is missing a value and in which table.

### CODE REVIEW

**Comment by bgruening** [comment]
Puh this is gross :)

Can you add a comment to the template generator why this is needed and do you see any way how we can test this?

**Comment by bedroesb** [comment]
@bgruening I know this does not look pretty ;) I found a nicer solution but problem is that the error that was thrown from the XSD validator was about the XML and not about to tsv/xlsx input file + it was not triggered when `<key></key>` was left empty....

When it comes to testing, we would need many files in the current situation, because it stops the script when it encounters the first one. I don't know if I can keep track in the template of the errors so if the XML generation is done I know in the main python script there where errors 🤔

**Comment by bgruening** [comment]
We need a rebase here :(
Sorry I was to late, feel free to merge, looks good to me

**Comment by bedroesb** [comment]
@bgruening wel good is relative, "Puh this is gross :)" still applies sadly haha! I think it might benefit to have a look in how we could change the way we fill in the XMLs currenlty

**Review by bgruening — APPROVED** [review]

**Pull request merged**
